# Changes here will be overwritten by Copier; NEVER EDIT MANUALLY
_commit: 66fd52c
_src_path: gh:schwallergroup/copier-liac-minimal
author_email: octavian.susanu@epfl.ch
author_name: Octavian Susanu
github_org: octav19
package_name: chemicalbd
project_name: chemicalbd
short_description: A program that offers possible disconnections of chemical bonds
